<?php
	// -------------------------------------- fsrp language definition file -----------------------------------
	$G_languages = array(
		"es" => "Español",
		"en" => "English"
	);
	
	$G_resource_strings = array(
		/* ------------------------------------------ ESPAÑOL ----------------------------------------------- */
		"es" =>
			array(
				"LANGUAGE_NAME"							=> "Español",
				"LANGUAGE_TRAD"							=> "Seleccionar Idioma",
				"APP_NAME"							=> "KINWIS",
				"HEADER_SUBTITLE"						=> "P a n e l - d e - Acceso",
				"FOOTER_VERSION"						=> "Versión",
				"USER_TYPE_ROOT"						=> "Root",
				"USER_TYPE_ADMN"						=> "Administrador",
				"USER_TYPE_RSLR"						=> "Estándar",
				"LINK_VIEW_TO"						    => "a",
				"LINK_VIEW_FOR"						    => "de",
				
				/* -- reseller home -------------------------------------------------------------------------- */
				"MENU_HOME"								=> "administración de sub-cuentas",
				"HOME_RESELLER_ACCT_INFO"				=> "INFORMACIÓN DE CUENTA (REVENDEDOR)",
				"HOME_SUBACCOUNT_LIST"					=> "LISTA DE SUB-CUENTAS",
				"HOME_SUBACCOUNT_NEW"					=> "AGREGAR SUB-CUENTA",
				"HOME_RESELLER"							=> "Revendedor",
				"HOME_LOGGED_ON_SINCE"					=> "Sesión Iniciada Desde",
				"HOME_SERVER_PORT_DES"					=> "Server:Port/DES Key",
				"HOME_CREDIT_PURCHASES"					=> "Compras de Créditos",
				"HOME_CREDIT_USAGE"						=> "Uso de Crédito",
				"HOME_CREDIT_BALANCE"					=> "Saldo de Crédito",
				"HOME_VIEW_DETAILS"						=> "Ver Detalles",
				"HOME_MONTHS"							=> "mes(es)",
				"HOME_LIST_SUBACCOUNT"					=> "Sub-cuenta",
				"HOME_LIST_PASSWORD"					=> "Contraseña",
				"HOME_LIST_COMMENTS"					=> "Comentarios",
				"HOME_LIST_EXPIRY_DATE"					=> "Fecha de Vencimiento",
				"HOME_LIST_IP"					        => "Ip",
				"HOME_LIST_CHANEL"					    => "Canal",
				"HOME_LIST_DURATION"                    => "Duración",
				"HOME_LIST_PAGE"						=> "Página",
				"HOME_LIST_OF"							=> "de",
				"HOME_LIST_GO"							=> "Ir",
				"HOME_LIST_EDIT"					    => "Editar",
				"HOME_ADD_SUBACCOUNT_INFO"				=> "Info. de Sub-cuenta",
				"HOME_ADD_USERNAME"						=> "Clave de Usuario",
				"HOME_ADD_PASSWORD"						=> "Contraseña",
				"HOME_ADD_COMMENT"						=> "Comentarios",
				"HOME_ADD_MONTHS"						=> "Mes(es)",
				"HOME_ADD_EXPIRY_DATE"					=> "Fecha de Vencimiento",
				"HOME_ADD_ADD"							=> "Agregar",
				"HOME_ADD_OBLIGATORY"					=> "La Clave de Usuario, Contraseña y Mes(es) son campos obligatorios al agregar una Sub-cuenta",
				"HOME_ADD_FAILED"						=> "Ocurrió un error al intentar agregar la cuenta (la cuenta del servidor si fue creada)",
				"HOME_ADD_ALREADY_EXISTS"				=> "Ocurrió un error al intentar agregar la cuenta. Ya existe una cuenta con el mismo nombre",
				"HOME_ADD_INSUFFICIENT_CREDIT"			=> "No es posible agregar la cuenta debido a que no tiene crédito suficiente",
				"HOME_ADD_CONFIRM"						=> "Se agregará la cuenta con la información y meses de servicio especificados, disminuyendo de su crédito disponible. Está seguro que desea continuar?",
				"HOME_ADD_DEMO_CONFIRM"					=> "Se agregará la cuenta DEMO por 1 día con la información especificada. Está seguro que desea continuar?",
				"HOME_NO_ACCOUNTS"						=> "No hay sub-cuentas",
				"HOME_SHOW"								=> "Mostrar",
				"HOME_SHOW_ALL"							=> "Todas las Sub-cuentas",
				"HOME_SHOW_NOT_EXPIRED"					=> "Sub-cuentas Vigentes",
				"HOME_SHOW_EXPIRED"						=> "Sub-cuentas Vencidas",
				"HOME_ORDER_BY"							=> "Ordenar Por",
				"HOME_ORDER_BY_SUBACCOUNT_NAME"			=> "Nombre de Sub-cuenta",
				"HOME_ORDER_BY_SUBACCOUNT_EXPIRY"		=> "Fecha de Vencimiento de Sub-cuenta",
				
				/* -- change settings ------------------------------------------------------------------------ */
				"MENU_CHANGE_SETTINGS"		            => "Ajuste del Sistema",
				"CHANGE_SETTINGS_SERVICE"		        => "Información del Servidor",
				"CHANGE_SETTINGS_ADJUSTE"		        => "Información del Mensajeria",
				"CHANGE_SETTINGS_ACTIVE"		        => "Activo",
				"CHANGE_SETTINGS_NO"		            => "No",
				"CHANGE_SETTINGS_YES"		            => "Si",
				"CHANGE_SETTINGS_IP_HOST"		        => "IP/Nombre de host",
				"CHANGE_SETTINGS_PORT"		            => "Puerto",
				"CHANGE_SETTINGS_USER"		            => "Nombre de usuario",
				"CHANGE_SETTINGS_PASS"		            => "Contraseña",
				"CHANGE_SETTINGS_PROT"		            => "Protocol",
				"CHANGE_SETTINGS_CONNCHK"		        => "Sistema",
				"CHANGE_SETTINGS_SAVE"		            => "Guardar",
				"CHANGE_SETTINGS_FAILURE"			    => "Ocurrió un error al actualizar la información",
				"CHANGE_SETTINGS_SUCCESSFULLY"          => "Información actualizar con éxito",
				"CHANGE_SETTINGS_SAVE_CONFIRM"			=> "La información será actualizada. Está seguro que desea continuar?",
				"CHANGE_SETTINGS_SAVE_OBLIGATORY"		=> "Los campos de Ip, Port, Nombre y Contraseña son obligatorios al actualizar la información",
				
				/* -- change password ------------------------------------------------------------------------ */
				"MENU_CHANGE_PASSWORD"					=> "cambiar contraseña",
				"CHANGE_PASSWORD_MESSAGE"				=> "Introduzca su contraseña actual y la contraseña nueva",
				"CHANGE_PASSWORD_OLD"					=> "Contraseña Actual",
				"CHANGE_PASSWORD_NEW"					=> "Contraseña Nueva",
				"CHANGE_PASSWORD_SUBMIT"				=> "Cambiar",
				"CHANGE_PASSWORD_NO_INFO"				=> "Debe especificar su contraseña actual y contraseña nueva",
				"CHANGE_PASSWORD_EQUAL_PASSWORDS"		=> "La contraseña actual y contraseña nueva deben ser distintas",
				"CHANGE_PASSWORD_SUCCESS"				=> "La contraseña ha sido cambiada exitosamente",
				"CHANGE_PASSWORD_FAILURE"				=> "Ocurrió un error al cambiar la contraseña actual",
				"CHANGE_PASSWORD_INVALID"				=> "La contraseña actual especificad es inválida",
				"CHANGE_PASSWORD_CONFIRM"				=> "La contraseña actual de la cuenta será cambiada. Está seguro que desea continuar?",
				
				/* -- user management ------------------------------------------------------------------------ */
				"MENU_ADMIN_SETTINGS"					=> "configuracion de conexión",
				"MENU_ADMIN_USER_MANAGEMENT"			=> "administración de super-revendedores",
				"MENU_ADMIN_USER_MANAGEMENT_USERS"		=> "CUENTAS DE SUPER-REVENDEDORES",
				"MENU_ADMIN_USER_MANAGEMENT_USER_NEW"	=> "AGREGAR CUENTA DE SUPER-REVENDEDOR",
				
				/* -- logout --------------------------------------------------------------------------------- */
				"MENU_LOGOUT"							=> "abandonar sesión",
				"MENU_LOGOUT_CONFIRM"					=> "Se cerrará la sesión actual. Está seguro que desea continuar?",
				
				/* -- admin home ----------------------------------------------------------------------------- */
				"MENU_ADMIN_HOME"						=> "administración de revendedores",
				"MENU_ADMIN_HOME_RESELLER_ACCOUNTS"		=> "CUENTAS DE REVENDEDORES",
				"MENU_ADMIN_HOME_RESELLER_NEW"			=> "AGREGAR CUENTA DE REVENDEDOR",
				
				/* -- login ---------------------------------------------------------------------------------- */
				"LOGIN_MESSAGE"							=> "Introduzca su clave de usuario y contraseña para iniciar",
				"LOGIN_USERNAME"						=> "Usuario",
				"LOGIN_PASSWORD"						=> "Contraseña",
				"LOGIN_SUBMIT"							=> "Iniciar",
				"LOGIN_NO_INFO"							=> "Debe especificar su clave de usuario y contraseña",
				"LOGIN_INVALID"							=> "La clave de usuario y contraseñas introducidas son inválidas",
				
	 			/* -- expiry check --------------------------------------------------------------------------- */
				"EXPIRY_CHECK_MESSAGE"					=> "Introduzca su cuenta y contraseña para obtener su fecha de vencimiento",
				"EXPIRY_CHECK_USERNAME"					=> "Cuenta",
				"EXPIRY_CHECK_PASSWORD"					=> "Contraseña",
				"EXPIRY_CHECK_SUBMIT"					=> "Obtener",
				"EXPIRY_CHECK_NO_INFO"					=> "Debe especificar su cuenta y contraseña",
				"EXPIRY_CHECK_INVALID"					=> "La cuenta y contraseñas introducidas son inválidas",
				"EXPIRY_CHECK_EXPIRES_ON"				=> "La cuenta expira el (aaaa-mm-dd)",
				"EXPIRY_CHECK_STATUS"					=> "Estatus",
				"EXPIRY_CHECK_STATUS_INACTIVE"			=> "Inactiva",
				"EXPIRY_CHECK_STATUS_ACTIVE"			=> "Activa",
				
				/* -- transaction history -------------------------------------------------------------------- */
				"TRANSACTION_HISTORY_RESELLER"			=> "Revendedor",
				"TRANSACTION_HISTORY_TRANSACTION"		=> "Transacción",
				"TRANSACTION_HISTORY_MONTHS_PURCHASED"	=> "Meses Comprados",
				"TRANSACTION_HISTORY_AMOUNT"			=> "Monto",
				"TRANSACTION_HISTORY_DATETIME"			=> "Fecha/Hora Trans.",
				"TRANSACTION_HISTORY_SUBACCOUNT"		=> "Sub-cuenta",
				"TRANSACTION_HISTORY_COVER_START"		=> "Inicio Cobertura",
				"TRANSACTION_HISTORY_COVER_END"			=> "Fin Cobertura",
				"TRANSACTION_HISTORY_NO_TRANSACTIONS"	=> "Sin transacciones",
				
				/* -- infobar -------------------------------------------------------------------------------- */
				"INFOBAR_USERNAME"						=> "Clave de Usuario",
				"INFOBAR_UNAUTHENTICATED"				=> "No Autentificado",
				"INFOBAR_USERNAME_NAME"					=> "Nombre",
				"INFOBAR_TYPE"							=> "Tipo",
				"INFOBAR_LAST_LOGIN"					=> "Último Acceso",

				/* -- account actions ----------------------------------------------------------------------- */
				"ACCOUNT_ACTIONS_INFO"					=> "INFORMACIÓN DE SUB-CUENTA",
				"ACCOUNT_ACTIONS_INFO_SEND_MSG"			=> "INFORMACIÓN ADICIONALES PARA ENVIO DE MENSAJE DE VENCIMIENTO DE LA SUB-CUENTA",
				"ACCOUNT_ACTIONS_TRANSACTION_HISTORY"	=> "HISTORIA DE TRANSACCIONES",
				"ACCOUNT_ACTIONS_SUBACCOUNT"			=> "Sub-cuenta",
				"ACCOUNT_ACTIONS_PASSWORD"				=> "Contraseña",
				"ACCOUNT_ACTIONS_COMMENTS"			    => "Comentarios",
				"ACCOUNT_ACTIONS_EMAIL"			        => "Correo",
				"ACCOUNT_ACTIONS_PHONE"			        => "Teléfono",
				"ACCOUNT_ACTIONS_STATUS"			    => "Estatus",
				"ACCOUNT_ACTIONS_BAN"			        => "Baneado por:",
				"ACCOUNT_ACTIONS_UPDATE"				=> "Actualizar",
				"ACCOUNT_ACTIONS_EXPIRY"				=> "Fecha de Vencimiento",
				"ACCOUNT_ACTIONS_TRANSACTION"			=> "Transacción",
				"ACCOUNT_ACTIONS_MONTHS_PURCHASED"		=> "Meses Comprados",
				"ACCOUNT_ACTIONS_COVERAGE_START"		=> "Inicio Cobertura",
				"ACCOUNT_ACTIONS_COVERAGE_END"			=> "Fin Cobertura",
				"ACCOUNT_ACTIONS_DATETIME"				=> "Fecha/Hora Trans.",
				"ACCOUNT_ACTIONS_UPDATE_SUCCESS"		=> "Los datos de la sub-cuenta se actualizaron correctamente",
				"ACCOUNT_ACTIONS_UPDATE_FAILURE"		=> "Ocurrió un error al actualizar los datos de la sub-cuenta",
				"ACCOUNT_ACTIONS_SERVER_INFO"			=> "INFORMACIÓN DE SUB-CUENTA EN SERVIDOR",
				"ACCOUNT_ACTIONS_SERVER_PASSWORD"		=> "Contraseña",
				"ACCOUNT_ACTIONS_SERVER_EXPIRY"			=> "Fecha de Vencimiento",
				"ACCOUNT_ACTIONS_SERVER_STATUS"			=> "Estatus",
				"ACCOUNT_ACTIONS_GET_SERVER_INFO"		=> "Obtener",
				"ACCOUNT_ACTIONS_SERVICE"				=> "SERVICIO",
				"ACCOUNT_ACTIONS_ADD_MONTHS"			=> "Agregar Meses Servicio",
				"ACCOUNT_ACTIONS_ADD"					=> "Agregar",
				"ACCOUNT_ACTIONS_ADD_CONFIRM"			=> "Se agregará a la cuenta los meses de servicio especificados, disminuyendo de su crédito disponible. Está seguro que desea continuar?",
				"ACCOUNT_ACTIONS_ADD_SUCCESS"			=> "Los meses de servicio especificados fueron agregados existosamente",
				"ACCOUNT_ACTIONS_ADD_FAILURE"			=> "Ocurrió un error al agregar los meses de servicio especificados",
				"ACCOUNT_ACTIONS_ADD_INSUFFICIENT"		=> "No es posible agregar los meses de servicio debido a que no tiene crédito suficiente.",
				"ACCOUNT_ACTIONS_NO_TRANSACTIONS"		=> "Sin transacciones",
				"ACCOUNT_ACTIONS_ACTIVE"				=> "Activo",
				"ACCOUNT_ACTIONS_INACTIVE"				=> "Inactivo",
				"ACCOUNT_ACTIONS_HELP_IDIOMA"			=> "Seleccionar el idioma para el envio de Recordatorio de Vencimiento de la cuenta.",
				
				/* -- user management ----------------------------------------------------------------------- */
				"MANAGEMENT_USERS_USERNAME"				=> "Clave de Usuario",
				"MANAGEMENT_USERS_NAME"					=> "Nombre",
				"MANAGEMENT_USERS_PASSWORD"				=> "Contraseña",
				"MANAGEMENT_USERS_TYPE"					=> "Tipo",
				"MANAGEMENT_USERS_STATUS"				=> "Estatus",
				"MANAGEMENT_USERS_CREDIT"				=> "Crédito",
				"MANAGEMENT_USERS_LAST_LOGIN"			=> "Ultima Sesión",
				"MANAGEMENT_USERS_ROOT"					=> "Root (Administrador)",
				"MANAGEMENT_USERS_ADMINISTRATOR"		=> "Super-revendedor",
				"MANAGEMENT_USERS_UNKNOWN"				=> "Desconocido",
				"MANAGEMENT_USERS_ACTIVE"				=> "Activo",
				"MANAGEMENT_USERS_SUSPENDED"			=> "Suspendido",
				"MANAGEMENT_USERS_SAVE_CONFIRM"			=> "La información del usuario seleccionado será actualizada. Está seguro que desea continuar?",
				"MANAGEMENT_USERS_SAVE"					=> "Guardar",
				"MANAGEMENT_USERS_EDIT"					=> "Editar",
				"MANAGEMENT_USERS_ADD_USERNAME"			=> "Clave de Usuario",
				"MANAGEMENT_USERS_ADD_NAME"				=> "Nombre",
				"MANAGEMENT_USERS_ADD_PASSWORD"			=> "Contraseña",
				"MANAGEMENT_USERS_ADD_ADD"				=> "Agregar",
				"MANAGEMENT_USERS_ADD_INFO"				=> "Información de Usuario",
				"MANAGEMENT_USERS_ADD_CONFIRM"			=> "Se agregará el usuario. Está seguro que desea continuar?",
				"MANAGEMENT_USERS_ADD_OBLIGATORY"		=> "Los campos de Clave de Usuario, Nombre y Contraseña son obligatorios al agregar un usuario",
				"MANAGEMENT_USERS_ADD_FAILURE"			=> "Ocurrió un error al agregar el usuario",
				"MANAGEMENT_USERS_SAVE_FAILURE"			=> "Ocurrió un error al actualizar la información del usuario",
				"MANAGEMENT_USERS_SAVE_OBLIGATORY"		=> "Los campos de Nombre y Contraseña son obligatorios al actualizar la información del usuario",
				"MANAGEMENT_USERS_DELETE"				=> "Eliminar",
				"MANAGEMENT_USERS_DELETE_CONFIRM"		=> "El usuario será eliminado. Está seguro que desea continuar?",
				"MANAGEMENT_USERS_DELETE_FAILURE"		=> "Ocurrió un error al eliminar el usuario",
				"MANAGEMENT_USERS_DELETE_FAILURE_EXIST"	=> "El super-revendedor no puede ser eliminado debido a relaciones con información existente (sub-cuentas, transacciones o revendedores). Elimínelas e intente nuevamente.",

				/* -- reseller management ------------------------------------------------------------------- */
				"RESELLER_MANAGEMENTS_NO_RESELLERS"			=> "No hay revendedores",
				"RESELLER_MANAGEMENT_OWNER"					=> "Propietario",
				"RESELLER_MANAGEMENT_NO_OWNER"				=> "Sin Propietario",
				"RESELLER_MANAGEMENT_USERNAME"				=> "Clave de Usuario",
				"RESELLER_MANAGEMENT_NAME"					=> "Nombre",
				"RESELLER_MANAGEMENT_PASSWORD"				=> "Contraseña",
				"RESELLER_MANAGEMENT_PREFIX"				=> "Prefijo",
				"RESELLER_MANAGEMENT_COMMENT"				=> "Comentarios",
				"RESELLER_MANAGEMENT_STATUS"				=> "Estatus",
				"RESELLER_MANAGEMENT_LAST_LOGIN"			=> "Ultima Sesión",
				"RESELLER_MANAGEMENT_UNKNOWN"				=> "Desconocido",
				"RESELLER_MANAGEMENT_ACTIVE"				=> "Activo",
				"RESELLER_MANAGEMENT_SUSPENDED"				=> "Suspendido",
				"RESELLER_MANAGEMENT_SAVE_CONFIRM"			=> "La información del revendedor seleccionado será actualizada. Está seguro que desea continuar?",
				"RESELLER_MANAGEMENT_SUBACCOUNTS"			=> "Cuentas",
				"RESELLER_MANAGEMENT_SAVE"					=> "Guardar",
				"RESELLER_MANAGEMENT_EDIT"					=> "Editar",
				"RESELLER_MANAGEMENT_ADD_USERNAME"			=> "Clave de Usuario",
				"RESELLER_MANAGEMENT_ADD_NAME"				=> "Nombre",
				"RESELLER_MANAGEMENT_ADD_PASSWORD"			=> "Contraseña",
				"RESELLER_MANAGEMENT_ADD_PREFIX"			=> "Prefijo de Cuentas",
				"RESELLER_MANAGEMENT_ADD_COMMENTS"			=> "Comentarios",
				"RESELLER_MANAGEMENT_ADD_ADD"				=> "Agregar",
				"RESELLER_MANAGEMENT_ADD_INFO"				=> "Información de Revendedor",
				"RESELLER_MANAGEMENT_ADD_CONFIRM"			=> "Se agregará el revendedor. Está seguro que desea continuar?",
				"RESELLER_MANAGEMENT_ADD_OBLIGATORY"		=> "Los campos de Clave de Usuario, Nombre y Contraseña son obligatorios al agregar un revendedor",
				"RESELLER_MANAGEMENT_ADD_FAILURE"			=> "Ocurrió un error al agregar el revendedor",
				"RESELLER_MANAGEMENT_ADD_ALREADY_EXISTS"	=> "No es posible agregar, el revendedor ya existe",
				"RESELLER_MANAGEMENT_SAVE_FAILURE"			=> "Ocurrió un error al actualizar la información del revendedor",
				"RESELLER_MANAGEMENT_SAVE_OBLIGATORY"		=> "Los campos de Nombre y Contraseña son obligatorios al actualizar la información del revendedor",
				"RESELLER_MANAGEMENT_DELETE"				=> "Eliminar",
				"RESELLER_MANAGEMENT_DELETE_CONFIRM"		=> "El revendedor será eliminado. Está seguro que desea continuar?",
				"RESELLER_MANAGEMENT_DELETE_FAILURE"		=> "Ocurrió un error al eliminar el revendedor",
				"RESELLER_MANAGEMENT_DELETE_FAILURE_EXIST"	=> "El revendedor no puede ser eliminado debido a historia relacionanda existente",

				/* -- reseller edit ------------------------------------------------------------------------- */
				"RESELLER_EDIT_ADD_SUCCESS"					=> "El crédito de revendedor fue agregado existosamente",
				"RESELLER_EDIT_ADD_FAILURE"					=> "Ocurrió un error al agregar el crédito de revendedor",
				"RESELLER_EDIT_INFO"						=> "INFORMACIÓN DE REVENDEDOR",
				"RESELLER_EDIT_RESELLER"					=> "Clave de Usuario",
				"RESELLER_EDIT_NAME"						=> "Nombre",
				"RESELLER_EDIT_STATUS"						=> "Estatus",
				"RESELLER_EDIT_ACTIVE"						=> "Activo",
				"RESELLER_EDIT_SUSPENDED"					=> "Suspendido",
				"RESELLER_EDIT_UNKNOWN"						=> "Desconocido",
				"RESELLER_EDIT_ADD_CREDIT"					=> "Agregar Meses de Crédito",
				"RESELLER_EDIT_ADD_CREDIT_USER"				=> "Crédito Disponibles",
				"RESELLER_EDIT_ADD_CREDIT_MESG"				=> "No Tienes los Créditos para Asignar",
				"RESELLER_EDIT_ADD_CONFIRM"					=> "Se agregarán el número de meses de crédito especificados. Está seguro que desea continuar?",
				"RESELLER_EDIT_ADD"							=> "Agregar",
				"RESELLER_EDIT_TRANSACTION_HISTORY"			=> "HISTORIA DE TRANSACCIONES",
				"RESELLER_EDIT_TRANSACTION"					=> "Transacción",
				"RESELLER_EDIT_TYPE"						=> "Tipo",
				"RESELLER_EDIT_MONTHS_PURCHASED"			=> "Meses",
				"RESELLER_EDIT_AMOUNT"						=> "Monto",
				"RESELLER_EDIT_SUBACCOUNT"					=> "Sub-cuenta",
				"RESELLER_EDIT_COVERAGE_START"				=> "Inico Cobertura",
				"RESELLER_EDIT_COVERAGE_END"				=> "Fin Cobertura",
				"RESELLER_EDIT_DATETIME"					=> "Fecha/Hora",
				"RESELLER_EDIT_CREDIT"						=> "Compra",
				"RESELLER_EDIT_DEBIT"						=> "Uso",
				"RESELLER_EDIT_UNKNOWN"						=> "Desconocido",
				"RESELLER_EDIT_NO_TRANSACTIONS"				=> "Sin transacciones",
				"RESELLER_EDIT_CREDIT_BALANCE"				=> "Saldo de Crédito",
				"RESELLER_EDIT_DELETE"						=> "Eliminar",
				"RESELLER_EDIT_DELETE_CONFIRM"				=> "La transacción especificada será eliminada. Está seguro que desea continuar?",
				"RESELLER_EDIT_DELETE_SUCCESS"				=> "La transacción especificada fue eliminada existosamente",
				"RESELLER_EDIT_DELETE_FAILURE"				=> "Ocurrió un error al eliminar la transacción especificada",
				"SUBACCOUNT_DELETE_SUCCESS"		=> "La sub-cuenta fue eliminadas existósamente",
				"SUBACCOUNT_DELETE_FAILURE"		=> "Ocurrió un error al eliminar la sub-cuenta",
				"SUBACCOUNT_DELETE_CONFIRM"		=> "La sub-cuenta especificada, serán eliminadas. Está seguro que desea continuar?",
				"SUBACCOUNT_SERVER_WASNT_DELETED"	=> "La cuenta del servidor no fue eliminada",
				/* -- reseller subaccounts ------------------------------------------------------------------ */
				"RESELLER_SUBACCOUNT_DELETE_SUCCESS"		=> "La sub-cuenta y sus transacciones fueron eliminadas existósamente",
				"RESELLER_SUBACCOUNT_DELETE_FAILURE"		=> "Ocurrió un error al eliminar la sub-cuenta o sus transacciones",
				"RESELLER_SUBACCOUNT_DELETE_CONFIRM"		=> "La sub-cuenta especificada, así como las transacciones asociadas a ella, serán eliminadas. Esto afectará el saldo de crédito del revendedor. Está seguro que desea continuar?",
				"RESELLER_SUBACCOUNT_LIST"					=> "LISTA DE SUB-CUENTAS",
				"RESELLER_SUBACCOUNT_MAX_LOGIN"		        => "Máximo Connection",
				"RESELLER_SUBACCOUNT_TRANSACTION_COUNT"		=> "Transacciones",
				"RESELLER_SUBACCOUNT_SERVER_WASNT_DELETED"	=> "La cuenta del servidor no fue eliminada",
				"RESELLER_SUBACCOUNT_ADD_CONFIRM"			=> "Se agregará la cuenta con la información y meses de servicio especificados, disminuyendo del crédito disponible del revendedor. Está seguro que desea continuar?",
				"RESELLER_SUBACCOUNT_EXPIRY_DATE_CHANGE"	=> "Modificar",
				"RESELLER_SUBACCOUNT_EXPIRY_DATE_SAVE"		=> "Guardar",
				"RESELLER_SUBACCOUNT_EXPIRY_DATE_CHANGE_CONFIRM"	=>	"La fecha de vencimiento de la sub-cuenta especificada será actualizada. Está seguro que desea continuar?",
				"RESELLER_SUBACCOUNT_MAX_LOGIN_CHANGE_CONFIRM"	=>	"El máximo connection de la sub-cuenta especificada será actualizada. Está seguro que desea continuar?",
				"RESELLER_SUBACCOUNT_EXPIRY_UPDATE_SUCCESS"	=> "La fecha de vencimiento de la sub-cuenta ha sido actualizada con éxito",
				"RESELLER_SUBACCOUNT_EXPIRY_UPDATE_FAILURE"	=> "Ocurrió un error al intentar actualizar la fecha de vencimiento de la sub-cuenta (la cuenta en el servidor fue actualizada correctamente)",
				"RESELLER_SUBACCOUNT_SERVER_WASNT_UPDATED"	=> "La fecha de vencimiento de la cuenta en el servidor no fue actualizada",
			),
		
		"en" =>
		/* ------------------------------------------ ENGLISH ----------------------------------------------- */
			array(
				"LANGUAGE_NAME"							=> "English",
				"LANGUAGE_TRAD"							=> "Select Language",
				"APP_NAME"							=> "Fireshare Reseller Panel",
				"HEADER_SUBTITLE"						=> "r e s e l l e r - p a n e l",
                "FOOTER_VERSION"                        => "Version",
				"USER_TYPE_ROOT"						=> "Root",
				"USER_TYPE_ADMN"						=> "Administrator",
				"USER_TYPE_RSLR"						=> "Standard",
				"LINK_VIEW_TO"						    => "to",
				"LINK_VIEW_FOR"						    => "by",

				/* -- reseller home -------------------------------------------------------------------------- */
				"MENU_HOME"								=> "sub-account management",
				"HOME_RESELLER_ACCT_INFO"				=> "RESELLER ACCOUNT INFORMATION",
				"HOME_SUBACCOUNT_LIST"					=> "SUB-ACCOUNT LIST",
				"HOME_SUBACCOUNT_NEW"					=> "ADD SUB-ACCOUNT",
				"HOME_RESELLER"							=> "Reseller",
				"HOME_LOGGED_ON_SINCE"					=> "Logged On Since:",
				"HOME_SERVER_PORT_DES"					=> "Server:Port/DES Key",
				"HOME_CREDIT_PURCHASES"					=> "Credit Purchases",
				"HOME_CREDIT_USAGE"						=> "Credit Usage",
				"HOME_CREDIT_BALANCE"					=> "Credit Balance",
				"HOME_VIEW_DETAILS"						=> "View Details",
				"HOME_MONTHS"							=> "month(s)",
				"HOME_LIST_SUBACCOUNT"					=> "Sub-account",
				"HOME_LIST_PASSWORD"					=> "Password",
				"HOME_LIST_COMMENTS"					=> "Comments",
				"HOME_LIST_EXPIRY_DATE"					=> "Expiry Date",
				"HOME_LIST_IP"					        => "Ip",
				"HOME_LIST_CHANEL"					    => "Channel",
				"HOME_LIST_DURATION"                    => "Duration",
				"HOME_LIST_PAGE"						=> "Page",
				"HOME_LIST_OF"							=> "of",
				"HOME_LIST_GO"							=> "Go",
				"HOME_LIST_EDIT"					    => "Edit",
				"HOME_ADD_SUBACCOUNT_INFO"				=> "Sub-account Info",
				"HOME_ADD_USERNAME"						=> "Username",
				"HOME_ADD_PASSWORD"						=> "Password",
				"HOME_ADD_COMMENT"						=> "Comments",
				"HOME_ADD_MONTHS"						=> "Month(s)",
				"HOME_ADD_EXPIRY_DATE"					=> "Expiry Date",
				"HOME_ADD_ADD"							=> "Add",
				"HOME_ADD_OBLIGATORY"					=> "The Username, Password and Month fields are obligatory when adding a sub-account",
				"HOME_ADD_FAILED"						=> "An error ocurred while adding the account (the server-side account was created successfully)",
				"HOME_ADD_ALREADY_EXISTS"				=> "Failed to add the account. An account with the same name already exists",
				"HOME_ADD_INSUFFICIENT_CREDIT"			=> "The account cannot be added due to insufficient credit",
				"HOME_ADD_CONFIRM"						=> "The account will be added with the information and selected number of months of service, substracting from your current credit balance. Are you sure you wish to proceed?",
				"HOME_NO_ACCOUNTS"						=> "No sub-accounts",
				"HOME_SHOW"								=> "Show",
				"HOME_SHOW_ALL"							=> "All Sub-accounts",
				"HOME_SHOW_NOT_EXPIRED"					=> "Current Sub-accounts",
				"HOME_SHOW_EXPIRED"						=> "Expired Sub-accounts",
				"HOME_ORDER_BY"							=> "Order By",
				"HOME_ORDER_BY_SUBACCOUNT_NAME"			=> "Sub-account Name",
				"HOME_ORDER_BY_SUBACCOUNT_EXPIRY"		=> "Sub-account Expiry Date",
				
                /* -- change settings ------------------------------------------------------------------------ */
				"MENU_CHANGE_SETTINGS"		            => "System Setup",
				"CHANGE_SETTINGS_SERVICE"		        => "Information Server",
				"CHANGE_SETTINGS_ADJUSTE"		        => "Information Messaging",
				"CHANGE_SETTINGS_ACTIVE"		        => "Active",
				"CHANGE_SETTINGS_NO"		            => "No",
				"CHANGE_SETTINGS_YES"		            => "Yes",
				"CHANGE_SETTINGS_IP_HOST"		        => "IP/Hostname",
				"CHANGE_SETTINGS_PORT"		            => "Port",
				"CHANGE_SETTINGS_USER"		            => "Username",
				"CHANGE_SETTINGS_PASS"		            => "Password",
				"CHANGE_SETTINGS_PROT"		            => "Protocol",
				"CHANGE_SETTINGS_CONNCHK"		        => "System",
				"CHANGE_SETTINGS_SAVE"		            => "SAVE",
				"CHANGE_SETTINGS_FAILURE"                => "Failed to update information",
				"CHANGE_SETTINGS_SUCCESSFULLY"          => "Information updated successfully",
				"CHANGE_SETTINGS_SAVE_CONFIRM"			=> "The information will be updated. Are you sure you wish to proceed?",
				"CHANGE_SETTINGS_SAVE_OBLIGATORY"		=> "Fields of Ip, Port, Name and Password are required to update the information",
				
				/* -- change password ------------------------------------------------------------------------ */
				"MENU_CHANGE_PASSWORD"					=> "change password",
				"CHANGE_PASSWORD_MESSAGE"				=> "Enter your current password and new password",
				"CHANGE_PASSWORD_OLD"					=> "Current Password",
				"CHANGE_PASSWORD_NEW"					=> "New Password",
				"CHANGE_PASSWORD_SUBMIT"				=> "Change",
				"CHANGE_PASSWORD_NO_INFO"				=> "Please specify your current and new password",
				"CHANGE_PASSWORD_EQUAL_PASSWORDS"		=> "The current and new password must be different",
				"CHANGE_PASSWORD_SUCCESS"				=> "The password was changed successfully",
				"CHANGE_PASSWORD_FAILURE"				=> "Failed to change the current password",
				"CHANGE_PASSWORD_INVALID"				=> "The specified current password is invalid",
				"CHANGE_PASSWORD_CONFIRM"				=> "Your current account password will be changed. Are you sure you wish to proceed?",
				
				/* -- user management ------------------------------------------------------------------------ */
				"MENU_ADMIN_SETTINGS"					=> "connection configuration",
				"MENU_ADMIN_USER_MANAGEMENT"			=> "super-reseller management",
				"MENU_ADMIN_USER_MANAGEMENT_USERS"		=> "SUPER-RESELLER ACCOUNTS",
				"MENU_ADMIN_USER_MANAGEMENT_USER_NEW"	=> "ADD SUPER-RESELLER ACCOUNT",

				/* -- logout --------------------------------------------------------------------------------- */
				"MENU_LOGOUT"							=> "logout",
				"MENU_LOGOUT_CONFIRM"					=> "The current session will be closed. Continue?",

				/* -- admin home ----------------------------------------------------------------------------- */
				"MENU_ADMIN_HOME"						=> "reseller management",
				"MENU_ADMIN_HOME_RESELLER_ACCOUNTS"		=> "RESELLER ACCOUNTS",
				"MENU_ADMIN_HOME_RESELLER_NEW"			=> "ADD RESELLER ACCOUNT",
				
				/* -- login ---------------------------------------------------------------------------------- */
				"LOGIN_MESSAGE"							=> "Enter your user name and password to start",
				"LOGIN_USERNAME"						=> "Username",
				"LOGIN_PASSWORD"						=> "Password",
				"LOGIN_SUBMIT"							=> "Start",
				"LOGIN_NO_INFO"							=> "Please specify your username and password",
				"LOGIN_INVALID"							=> "The specified username and password are invalid",
				
				/* -- expiry check --------------------------------------------------------------------------- */
				"EXPIRY_CHECK_MESSAGE"					=> "Enter your account name and password to retrieve the expiry date",
				"EXPIRY_CHECK_USERNAME"					=> "Account",
				"EXPIRY_CHECK_PASSWORD"					=> "Password",
				"EXPIRY_CHECK_SUBMIT"					=> "Retrieve",
				"EXPIRY_CHECK_NO_INFO"					=> "You must specify your account name and password",
				"EXPIRY_CHECK_INVALID"					=> "The specified account name and password are invalid",
				"EXPIRY_CHECK_EXPIRES_ON"				=> "The account expires on (yyyy-mm-dd)",
				"EXPIRY_CHECK_STATUS"					=> "Status",
				"EXPIRY_CHECK_STATUS_INACTIVE"			=> "Inactive",
				"EXPIRY_CHECK_STATUS_ACTIVE"			=> "Active",
				
				/* -- transaction history -------------------------------------------------------------------- */
				"TRANSACTION_HISTORY_RESELLER"			=> "Reseller",
				"TRANSACTION_HISTORY_TRANSACTION"		=> "Transaction",
				"TRANSACTION_HISTORY_MONTHS_PURCHASED"	=> "Months Purchased",
				"TRANSACTION_HISTORY_AMOUNT"			=> "Amount",
				"TRANSACTION_HISTORY_DATETIME"			=> "Trans. Date/Time",
				"TRANSACTION_HISTORY_SUBACCOUNT"		=> "Sub-account",
				"TRANSACTION_HISTORY_COVER_START"		=> "Coverage Start",
				"TRANSACTION_HISTORY_COVER_END"			=> "Coverage End",
				"TRANSACTION_HISTORY_NO_TRANSACTIONS"	=> "No transactions",
				
				/* -- infobar -------------------------------------------------------------------------------- */
				"INFOBAR_USERNAME"						=> "Username",
				"INFOBAR_UNAUTHENTICATED"				=> "Unauthenticated",
				"INFOBAR_USERNAME_NAME"					=> "Name",
				"INFOBAR_TYPE"							=> "Type",
				"INFOBAR_LAST_LOGIN"					=> "Last Login",

				/* -- account actions ----------------------------------------------------------------------- */
				"ACCOUNT_ACTIONS_INFO"					=> "SUB-ACCOUNT INFORMATION",
				"ACCOUNT_ACTIONS_INFO_SEND_MSG"			=> "ADDITIONAL INFORMATION SEND MESSAGE EXPIRATION OF SUB-ACCOUNT",
				"ACCOUNT_ACTIONS_TRANSACTION_HISTORY"	=> "TRANSACTION HISTORY",
				"ACCOUNT_ACTIONS_SUBACCOUNT"			=> "Sub-account",
				"ACCOUNT_ACTIONS_PASSWORD"				=> "Password",
				"ACCOUNT_ACTIONS_COMMENTS"			    => "Comments",
				"ACCOUNT_ACTIONS_EMAIL"			        => "Email",
				"ACCOUNT_ACTIONS_PHONE"			        => "Phone",
				"ACCOUNT_ACTIONS_STATUS"			    => "Status",
				"ACCOUNT_ACTIONS_BAN"			        => "Banned for:",
				"ACCOUNT_ACTIONS_UPDATE"				=> "Update",
				"ACCOUNT_ACTIONS_EXPIRY"				=> "Expiry Date",
				"ACCOUNT_ACTIONS_TRANSACTION"			=> "Transaction",
				"ACCOUNT_ACTIONS_MONTHS_PURCHASED"		=> "Months Purchased",
				"ACCOUNT_ACTIONS_COVERAGE_START"		=> "Coverage Start",
				"ACCOUNT_ACTIONS_COVERAGE_END"			=> "Coverage End",
				"ACCOUNT_ACTIONS_DATETIME"				=> "Trans. Date/Time",
				"ACCOUNT_ACTIONS_UPDATE_SUCCESS"		=> "The sub-account information was updated successfully",
				"ACCOUNT_ACTIONS_UPDATE_FAILURE"		=> "Failed to update the sub-account information",
				"ACCOUNT_ACTIONS_SERVER_INFO"			=> "SERVER-SIDE SUB-ACCOUNT INFORMATION",
				"ACCOUNT_ACTIONS_SERVICE"				=> "SERVICE",
				"ACCOUNT_ACTIONS_SERVER_PASSWORD"		=> "Password",
				"ACCOUNT_ACTIONS_SERVER_EXPIRY"			=> "Expiry Date",
				"ACCOUNT_ACTIONS_SERVER_STATUS"			=> "Status",
				"ACCOUNT_ACTIONS_GET_SERVER_INFO"		=> "Retrieve",
				"ACCOUNT_ACTIONS_ADD_MONTHS"			=> "Add Service Months",
				"ACCOUNT_ACTIONS_ADD"					=> "Add",
				"ACCOUNT_ACTIONS_ADD_CONFIRM"			=> "The specified number of service months will be added to the account, substracting from your current credit balance. Are you sure you wish to proceed?",
				"ACCOUNT_ACTIONS_ADD_SUCCESS"			=> "The specified service months were added successfully",
				"ACCOUNT_ACTIONS_ADD_FAILURE"			=> "Failed to add the specified service months",
				"ACCOUNT_ACTIONS_ADD_INSUFFICIENT"		=> "You can not add the months of service because they do not have enough credits.",
				"ACCOUNT_ACTIONS_NO_TRANSACTIONS"		=> "No transactions",
				"ACCOUNT_ACTIONS_ACTIVE"				=> "Active",
				"ACCOUNT_ACTIONS_INACTIVE"				=> "Inactive",
				"ACCOUNT_ACTIONS_HELP_IDIOMA"			=> "Select the language for sending tickler account.",

				/* -- user management ----------------------------------------------------------------------- */
				"MANAGEMENT_USERS_USERNAME"				=> "Username",
				"MANAGEMENT_USERS_NAME"					=> "Name",
				"MANAGEMENT_USERS_PASSWORD"				=> "Password",
				"MANAGEMENT_USERS_TYPE"					=> "Type",
				"MANAGEMENT_USERS_STATUS"				=> "Status",
				"MANAGEMENT_USERS_CREDIT"				=> "Credit",
				"MANAGEMENT_USERS_LAST_LOGIN"			=> "Last Login",
				"MANAGEMENT_USERS_ROOT"					=> "Root (Administrator)",
				"MANAGEMENT_USERS_ADMINISTRATOR"		=> "Super-reseller",
				"MANAGEMENT_USERS_UNKNOWN"				=> "Unknown",
				"MANAGEMENT_USERS_ACTIVE"				=> "Active",
				"MANAGEMENT_USERS_SUSPENDED"			=> "Suspended",
				"MANAGEMENT_USERS_SAVE_CONFIRM"			=> "The selected user information will be updated. Are you sure you wish to proceed?",
				"MANAGEMENT_USERS_SAVE"					=> "Save",
				"MANAGEMENT_USERS_EDIT"					=> "Edit",
				"MANAGEMENT_USERS_ADD_USERNAME"			=> "Username",
				"MANAGEMENT_USERS_ADD_NAME"				=> "Name",
				"MANAGEMENT_USERS_ADD_PASSWORD"			=> "Password",
				"MANAGEMENT_USERS_ADD_ADD"				=> "Add",
				"MANAGEMENT_USERS_ADD_INFO"				=> "User Information",
				"MANAGEMENT_USERS_ADD_CONFIRM"			=> "The user will be added. Are you sure you wish to proceed?",
				"MANAGEMENT_USERS_ADD_OBLIGATORY"		=> "The Username, Name and Password fields are obligatory when adding a user",
				"MANAGEMENT_USERS_ADD_FAILURE"			=> "Failed to add user",
				"MANAGEMENT_USERS_SAVE_FAILURE"			=> "Failed to update user information",
				"MANAGEMENT_USERS_SAVE_OBLIGATORY"		=> "The Name and Password fields are obligatory when updating user information",
				"MANAGEMENT_USERS_DELETE"				=> "Delete",
				"MANAGEMENT_USERS_DELETE_CONFIRM"		=> "The user will be deleted. Are you sure you wish to proceed?",
				"MANAGEMENT_USERS_DELETE_FAILURE"		=> "Failed to delete user",
				"MANAGEMENT_USERS_DELETE_FAILURE_EXIST"	=> "The super-reseller cannot be deleted due to existing related information (sub-accounts, transactions or resellers). Delete related data and try again.",
				
				/* -- reseller management ------------------------------------------------------------------- */
				"RESELLER_MANAGEMENTS_NO_RESELLERS"			=> "No resellers",
				"RESELLER_MANAGEMENT_OWNER"					=> "Owner",
				"RESELLER_MANAGEMENT_NO_OWNER"				=> "No Owner",
				"RESELLER_MANAGEMENT_USERNAME"				=> "Username",
				"RESELLER_MANAGEMENT_NAME"					=> "Name",
				"RESELLER_MANAGEMENT_PASSWORD"				=> "Password",
				"RESELLER_MANAGEMENT_PREFIX"				=> "Prefix",
				"RESELLER_MANAGEMENT_COMMENT"				=> "Comments",
				"RESELLER_MANAGEMENT_STATUS"				=> "Status",
				"RESELLER_MANAGEMENT_LAST_LOGIN"			=> "Last Login",
				"RESELLER_MANAGEMENT_UNKNOWN"				=> "Unknown",
				"RESELLER_MANAGEMENT_ACTIVE"				=> "Active",
				"RESELLER_MANAGEMENT_SUSPENDED"				=> "Suspended",
				"RESELLER_MANAGEMENT_SAVE_CONFIRM"			=> "The selected reseller information will be updated. Are you sure you wish to proceed?",
				"RESELLER_MANAGEMENT_SUBACCOUNTS"			=> "Accounts",
				"RESELLER_MANAGEMENT_SAVE"					=> "Save",
				"RESELLER_MANAGEMENT_EDIT"					=> "Edit",
				"RESELLER_MANAGEMENT_ADD_USERNAME"			=> "Username",
				"RESELLER_MANAGEMENT_ADD_NAME"				=> "Name",
				"RESELLER_MANAGEMENT_ADD_PASSWORD"			=> "Password",
				"RESELLER_MANAGEMENT_ADD_PREFIX"			=> "Accounts Prefix",
				"RESELLER_MANAGEMENT_ADD_COMMENTS"			=> "Comments",
				"RESELLER_MANAGEMENT_ADD_ADD"				=> "Add",
				"RESELLER_MANAGEMENT_ADD_INFO"				=> "Reseller Information",
				"RESELLER_MANAGEMENT_ADD_CONFIRM"			=> "The reseller will be added. Are you sure you wish to proceed?",
				"RESELLER_MANAGEMENT_ADD_OBLIGATORY"		=> "The Username, Name and Password fields are obligatory when adding a reseller",
				"RESELLER_MANAGEMENT_ADD_FAILURE"			=> "Failed to add reseller",
				"RESELLER_MANAGEMENT_ADD_ALREADY_EXISTS"	=> "Failed, the reseller already exists",
				"RESELLER_MANAGEMENT_SAVE_FAILURE"			=> "Failed to update reseller information",
				"RESELLER_MANAGEMENT_SAVE_OBLIGATORY"		=> "The Name and Password fields are obligatory when updating reseller information",
				"RESELLER_MANAGEMENT_DELETE"				=> "Delete",
				"RESELLER_MANAGEMENT_DELETE_CONFIRM"		=> "The reseller will be deleted. Are you sure you wish to proceed?",
				"RESELLER_MANAGEMENT_DELETE_FAILURE"		=> "Failed to delete reseller",
				"RESELLER_MANAGEMENT_DELETE_FAILURE_EXIST"	=> "The reseller cannot be deleted due to existing related history",
				
				/* -- reseller edit ------------------------------------------------------------------------- */
				"RESELLER_EDIT_ADD_SUCCESS"					=> "The reseller credit was added successfully",
				"RESELLER_EDIT_ADD_FAILURE"					=> "Failed to add reseller credit",
				"RESELLER_EDIT_INFO"						=> "RESELLER INFORMATION",
				"RESELLER_EDIT_RESELLER"					=> "Username",
				"RESELLER_EDIT_NAME"						=> "Name",
				"RESELLER_EDIT_STATUS"						=> "Status",
				"RESELLER_EDIT_ACTIVE"						=> "Active",
				"RESELLER_EDIT_SUSPENDED"					=> "Suspended",
				"RESELLER_EDIT_UNKNOWN"						=> "Unknown",
				"RESELLER_EDIT_ADD_CREDIT"					=> "Add Credit Months",
				"RESELLER_EDIT_ADD_CREDIT_USER"				=> "Credit Available",
				"RESELLER_EDIT_ADD_CREDIT_MESG"				=> "You have to assign the credits",
				"RESELLER_EDIT_ADD_CONFIRM"					=> "The selected number of credit months will be added. Are you sure you wish to proceed?",
				"RESELLER_EDIT_ADD"							=> "Add",
				"RESELLER_EDIT_TRANSACTION_HISTORY"			=> "TRANSACTION HISTORY",
				"RESELLER_EDIT_TRANSACTION"					=> "Transaction",
				"RESELLER_EDIT_TYPE"						=> "Type",
				"RESELLER_EDIT_MONTHS_PURCHASED"			=> "Months",
				"RESELLER_EDIT_AMOUNT"						=> "Amount",
				"RESELLER_EDIT_SUBACCOUNT"					=> "Sub-account",
				"RESELLER_EDIT_COVERAGE_START"				=> "Coverage Start",
				"RESELLER_EDIT_COVERAGE_END"				=> "Coverage End",
				"RESELLER_EDIT_DATETIME"					=> "Date/Time",
				"RESELLER_EDIT_CREDIT"						=> "Purchase",
				"RESELLER_EDIT_DEBIT"						=> "Usage",
				"RESELLER_EDIT_UNKNOWN"						=> "Unknown",
				"RESELLER_EDIT_NO_TRANSACTIONS"				=> "No transactions",
				"RESELLER_EDIT_CREDIT_BALANCE"				=> "Credit Balance",
				"RESELLER_EDIT_DELETE"						=> "Delete",
				"RESELLER_EDIT_DELETE_CONFIRM"				=> "The specified transaction will be deleted. Are you sure you wish to proceed?",
				"RESELLER_EDIT_DELETE_SUCCESS"				=> "The specified transaction was deleted successfully",
				"RESELLER_EDIT_DELETE_FAILURE"				=> "Failed to add the reseller credit",
				"SUBACCOUNT_DELETE_SUCCESS"		=> "The sub-account  were deleted successfully",
				"SUBACCOUNT_DELETE_FAILURE"		=> "Failed to delete sub-account",
				"SUBACCOUNT_DELETE_CONFIRM"		=> "The specified sub-account, will be deleted. Are you sure you wish to proceed?",
				"SUBACCOUNT_SERVER_WASNT_DELETED"	=> "Server account wasn't deleted",
				/* -- reseller subaccounts ------------------------------------------------------------------ */
				"RESELLER_SUBACCOUNT_DELETE_SUCCESS"		=> "The sub-account and its related transactions were deleted successfully",
				"RESELLER_SUBACCOUNT_DELETE_FAILURE"		=> "Failed to delete sub-account or its transactions",
				"RESELLER_SUBACCOUNT_DELETE_CONFIRM"		=> "The specified sub-account, as well as its associated transactions, will be deleted. This will affect the credit balance of the reseller. Are you sure you wish to proceed?",
				"RESELLER_SUBACCOUNT_LIST"					=> "SUB-ACCOUNT LIST",
				"RESELLER_SUBACCOUNT_MAX_LOGIN"		        => "Maximum Connection",
				"RESELLER_SUBACCOUNT_TRANSACTION_COUNT"		=> "Transactions",
				"RESELLER_SUBACCOUNT_SERVER_WASNT_DELETED"	=> "Server account wasn't deleted",
				"RESELLER_SUBACCOUNT_ADD_CONFIRM"			=> "The account will be added with the information and selected number of months of service, substracting from the credit balance of the reseller. Are you sure you wish to proceed?",
				"RESELLER_SUBACCOUNT_EXPIRY_DATE_CHANGE"	=> "Change",
				"RESELLER_SUBACCOUNT_EXPIRY_DATE_SAVE"		=> "Save",
				"RESELLER_SUBACCOUNT_EXPIRY_DATE_CHANGE_CONFIRM"	=>	"The expiry date for the selected sub-account will be updated. Are you sure you wish to proceed?",
				"RESELLER_SUBACCOUNT_MAX_LOGIN_CHANGE_CONFIRM"	=>	"The maximum connection for the selected sub-account will be updated. Are you sure you wish to proceed?",
				"RESELLER_SUBACCOUNT_EXPIRY_UPDATE_SUCCESS"	=> "The sub-account expiry date was updated successfully",
				"RESELLER_SUBACCOUNT_EXPIRY_UPDATE_FAILURE"	=> "Failed to update the sub-account expiry date (the server-side account was updated successfully)",
				"RESELLER_SUBACCOUNT_SERVER_WASNT_UPDATED"	=> "The server-side account expiry date wasn't updated",
		)
	);
	
	function grs( $resource_name )
	{
		global $G_resource_strings;
		global $G_current_language;

		return $G_resource_strings[$G_current_language][$resource_name];
	}

	function grse( $resource_name )
	{
		echo( grs( $resource_name ) );
	}
?>
